# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import sys
sys.path.append('../assets')
import overlayResources

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.WindowModality.NonModal)
        MainWindow.resize(600, 300)
        MainWindow.setAcceptDrops(False)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.imgBaseOverlay = QtWidgets.QLabel(parent=self.centralwidget)
        self.imgBaseOverlay.setGeometry(QtCore.QRect(0, 0, 600, 300))
        self.imgBaseOverlay.setText("")
        self.imgBaseOverlay.setPixmap(QtGui.QPixmap(":/images/base overlay.png"))
        self.imgBaseOverlay.setScaledContents(False)
        self.imgBaseOverlay.setObjectName("imgBaseOverlay")
        self.imgBtnOne = QtWidgets.QLabel(parent=self.centralwidget)
        self.imgBtnOne.setEnabled(True)
        self.imgBtnOne.setGeometry(QtCore.QRect(0, 0, 600, 300))
        self.imgBtnOne.setText("")
        self.imgBtnOne.setPixmap(QtGui.QPixmap(":/images/1.png"))
        self.imgBtnOne.setObjectName("imgBtnOne")
        self.imgBtnTwo = QtWidgets.QLabel(parent=self.centralwidget)
        self.imgBtnTwo.setEnabled(True)
        self.imgBtnTwo.setGeometry(QtCore.QRect(0, 0, 600, 300))
        self.imgBtnTwo.setText("")
        self.imgBtnTwo.setPixmap(QtGui.QPixmap(":/images/2.png"))
        self.imgBtnTwo.setObjectName("imgBtnTwo")
        self.imgBtnThree = QtWidgets.QLabel(parent=self.centralwidget)
        self.imgBtnThree.setEnabled(True)
        self.imgBtnThree.setGeometry(QtCore.QRect(0, 0, 600, 300))
        self.imgBtnThree.setText("")
        self.imgBtnThree.setPixmap(QtGui.QPixmap(":/images/3.png"))
        self.imgBtnThree.setObjectName("imgBtnThree")
        self.imgBtnFour = QtWidgets.QLabel(parent=self.centralwidget)
        self.imgBtnFour.setEnabled(True)
        self.imgBtnFour.setGeometry(QtCore.QRect(0, 0, 600, 300))
        self.imgBtnFour.setText("")
        self.imgBtnFour.setPixmap(QtGui.QPixmap(":/images/4.png"))
        self.imgBtnFour.setObjectName("imgBtnFour")
        self.imgBtnHeat = QtWidgets.QLabel(parent=self.centralwidget)
        self.imgBtnHeat.setEnabled(True)
        self.imgBtnHeat.setGeometry(QtCore.QRect(0, 0, 600, 300))
        self.imgBtnHeat.setText("")
        self.imgBtnHeat.setPixmap(QtGui.QPixmap(":/images/heat.png"))
        self.imgBtnHeat.setObjectName("imgBtnHeat")
        self.imgBtnRage = QtWidgets.QLabel(parent=self.centralwidget)
        self.imgBtnRage.setEnabled(True)
        self.imgBtnRage.setGeometry(QtCore.QRect(0, 0, 600, 300))
        self.imgBtnRage.setText("")
        self.imgBtnRage.setPixmap(QtGui.QPixmap(":/images/rage.png"))
        self.imgBtnRage.setObjectName("imgBtnRage")
        self.imgBtnUp = QtWidgets.QLabel(parent=self.centralwidget)
        self.imgBtnUp.setEnabled(True)
        self.imgBtnUp.setGeometry(QtCore.QRect(0, 0, 600, 300))
        self.imgBtnUp.setText("")
        self.imgBtnUp.setPixmap(QtGui.QPixmap(":/images/up.png"))
        self.imgBtnUp.setObjectName("imgBtnUp")
        self.imgBtnDown = QtWidgets.QLabel(parent=self.centralwidget)
        self.imgBtnDown.setEnabled(True)
        self.imgBtnDown.setGeometry(QtCore.QRect(0, 0, 600, 300))
        self.imgBtnDown.setText("")
        self.imgBtnDown.setPixmap(QtGui.QPixmap(":/images/down.png"))
        self.imgBtnDown.setObjectName("imgBtnDown")
        self.imgBtnLeft = QtWidgets.QLabel(parent=self.centralwidget)
        self.imgBtnLeft.setEnabled(True)
        self.imgBtnLeft.setGeometry(QtCore.QRect(0, 0, 600, 300))
        self.imgBtnLeft.setText("")
        self.imgBtnLeft.setPixmap(QtGui.QPixmap(":/images/left.png"))
        self.imgBtnLeft.setObjectName("imgBtnLeft")
        self.imgBtnRight = QtWidgets.QLabel(parent=self.centralwidget)
        self.imgBtnRight.setEnabled(True)
        self.imgBtnRight.setGeometry(QtCore.QRect(0, 0, 600, 300))
        self.imgBtnRight.setText("")
        self.imgBtnRight.setPixmap(QtGui.QPixmap(":/images/right.png"))
        self.imgBtnRight.setObjectName("imgBtnRight")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 33))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
